-- Populate achievements table with AICMT International certifications, awards, and milestones
INSERT INTO achievements (title, description, date_achieved, category, image_url, display_order, is_featured) VALUES
('ISO 14001:2015 Environmental Management Certification', 'Achieved international certification for environmental management systems, demonstrating our commitment to reducing environmental impact and improving sustainability practices.', '2020-03-15', 'certification', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=ISO%2014001%20environmental%20certification%20award%20certificate%20on%20office%20wall%20professional%20lighting&image_size=landscape_4_3', 1, true),
('B-Corp Certification', 'Certified as a Benefit Corporation, meeting rigorous standards of social and environmental performance, accountability, and transparency.', '2021-06-20', 'certification', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=B-Corp%20certification%20badge%20sustainable%20business%20award%20modern%20office%20setting&image_size=square_hd', 2, true),
('Asia Packaging Innovation Award 2022', 'Recognized for breakthrough biodegradable packaging solution that reduces plastic waste by 85% while maintaining product integrity.', '2022-09-10', 'award', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=packaging%20innovation%20award%20trophy%20sustainable%20materials%20conference%20stage&image_size=portrait_4_3', 3, true),
('Carbon Neutral Certification', 'Achieved carbon neutrality across all operations through renewable energy adoption and verified carbon offset programs.', '2022-12-01', 'certification', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=carbon%20neutral%20certification%20green%20energy%20solar%20panels%20factory%20roof&image_size=landscape_16_9', 4, true),
('Patent for Bio-Composite Material', 'Granted patent for innovative bio-composite packaging material made from agricultural waste and natural polymers.', '2021-11-30', 'patent', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=patent%20certificate%20bio-composite%20material%20laboratory%20research%20development&image_size=landscape_4_3', 5, false),
('Export Excellence Award', 'Recognized by the Ministry of Trade for outstanding export performance and contribution to sustainable packaging solutions globally.', '2023-04-18', 'award', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=export%20excellence%20award%20international%20trade%20ceremony%20government%20recognition&image_size=portrait_4_3', 6, false),
('ISO 9001:2015 Quality Management Certification', 'Certified for quality management systems ensuring consistent delivery of high-quality sustainable packaging solutions.', '2019-08-12', 'certification', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=ISO%209001%20quality%20management%20certification%20manufacturing%20facility%20quality%20control&image_size=landscape_4_3', 7, false),
('1 Million Units Milestone', 'Reached production milestone of 1 million sustainable packaging units, preventing 500 tons of plastic waste from entering the environment.', '2023-01-15', 'milestone', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=production%20milestone%20celebration%20factory%20workers%20sustainable%20packaging%20achievement&image_size=landscape_16_9', 8, true),
('Green Technology Innovation Grant', 'Awarded government grant for developing next-generation compostable packaging technology using marine algae.', '2023-07-22', 'award', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=green%20technology%20innovation%20grant%20marine%20algae%20research%20laboratory%20equipment&image_size=square_hd', 9, false),
('Zero Waste to Landfill Achievement', 'Achieved zero waste to landfill status across all manufacturing facilities through comprehensive recycling and circular economy practices.', '2023-10-05', 'milestone', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=zero%20waste%20achievement%20recycling%20facility%20circular%20economy%20sustainable%20manufacturing&image_size=landscape_4_3', 10, true);