-- Populate journey_milestones table with company timeline data
INSERT INTO journey_milestones (year, title, description, image_url, display_order, is_active) VALUES
('2018', 'Company Founded', 'AICMT International was founded with a mission to revolutionize packaging through sustainable plastic alternatives. Started in a small garage with big dreams.', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=modern%20startup%20garage%20office%20with%20sustainable%20packaging%20prototypes%20on%20tables%2C%20bright%20lighting%2C%20professional%20photography&image_size=landscape_4_3', 1, true),
('2018', 'First Product Launch', 'Successfully launched our first biodegradable packaging solution made from plant-based materials, marking our entry into the sustainable packaging market.', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=eco%20friendly%20biodegradable%20packaging%20products%20displayed%20on%20clean%20white%20background%2C%20professional%20product%20photography&image_size=landscape_4_3', 2, true),
('2019', 'Series A Funding', 'Secured $2.5M in Series A funding to scale production and expand our research and development capabilities for innovative sustainable materials.', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=modern%20business%20meeting%20room%20with%20investors%20shaking%20hands%2C%20professional%20corporate%20setting&image_size=landscape_4_3', 3, true),
('2020', 'Manufacturing Facility', 'Opened our first dedicated manufacturing facility with state-of-the-art equipment for producing sustainable packaging at scale.', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=modern%20eco%20friendly%20manufacturing%20facility%20interior%20with%20sustainable%20packaging%20production%20line&image_size=landscape_4_3', 4, true),
('2020', 'B-Corp Certification', 'Achieved B-Corporation certification, demonstrating our commitment to social and environmental responsibility in all business practices.', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=B%20Corporation%20certification%20ceremony%20with%20team%20celebrating%2C%20professional%20office%20environment&image_size=landscape_4_3', 5, true),
('2021', 'International Expansion', 'Expanded operations to Europe and Asia, establishing partnerships with major retailers committed to sustainable packaging solutions.', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=world%20map%20showing%20global%20expansion%20with%20sustainable%20packaging%20icons%2C%20modern%20infographic%20style&image_size=landscape_4_3', 6, true),
('2021', 'Carbon Neutral Achievement', 'Became the first packaging company in our region to achieve carbon neutrality across our entire supply chain and operations.', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=carbon%20neutral%20certificate%20with%20green%20energy%20symbols%20and%20sustainable%20factory%20background&image_size=landscape_4_3', 7, true),
('2022', 'Innovation Lab Opening', 'Opened our dedicated R&D Innovation Lab focused on developing next-generation biodegradable materials and smart packaging solutions.', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=modern%20research%20laboratory%20with%20scientists%20working%20on%20sustainable%20materials%2C%20high%20tech%20equipment&image_size=landscape_4_3', 8, true),
('2023', '100M Units Milestone', 'Reached the milestone of 100 million sustainable packaging units produced, preventing over 50 tons of traditional plastic waste.', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=celebration%20milestone%20infographic%20showing%20100%20million%20sustainable%20packages%20with%20environmental%20impact&image_size=landscape_4_3', 9, true),
('2024', 'AI-Powered Solutions', 'Launched AI-powered packaging optimization platform that helps clients reduce material usage by up to 30% while maintaining product protection.', 'https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=AI%20technology%20interface%20showing%20packaging%20optimization%20algorithms%20with%20sustainable%20materials&image_size=landscape_4_3', 10, true);